const images = {
  logo: require('./../assets/images/mypetlogo.png'),
  tips1: require('./../assets/images/tips1.png'),
  tips2: require('./../assets/images/tips2.png'),
  tips3: require('./../assets/images/tips3.png'),
  tips4: require('./../assets/images/tips4.png'),
  larrow: require('./../assets/images/leftarrow.png'),
  face: require('./../assets/images/faceid.png'),
  back: require('./../assets/images/backArrow.png'),
  searchicon: require('./../assets/images/icon_search.png'),
  menu: require('./../assets/images/iconmenu.png'),
  info: require('./../assets/images/compimage.png'),
  rarrow: require('./../assets/images/rightarrow.png'),
  cat: require('./../assets/images/cat.png'),
  dog: require('./../assets/images/dog.png'),
  profile: require('./../assets/images/profile.png'),
  instagram: require('./../assets/images/instagram.png'),
  facebook: require('./../assets/images/facebook.png'),
  twitter: require('./../assets/images/twitter.png'),
  star: require('./../assets/images/star.png'),
  splash: require('./../assets/images/splash.png'),
  google: require('./../assets/images/google.png'),
};

export default images;
